import requests
import json
import os
import numpy as np
import nibabel as nib
import time

BASE_URL = "http://127.0.0.1:8000/api/v1"
TEST_EMAIL = "test_doctor@example.com"
TEST_PASSWORD = "password123"
TEST_FILE_PATH = "debug_scan_2d.nii.gz"

def create_dummy_2d_nifti():
    """Create a dummy 2D-like NIfTI file (simulating a single slice)"""
    print("Creating dummy 2D NIfTI file (512x512x1)...")
    # Shape (512, 512, 1)
    data = np.random.rand(512, 512, 1).astype(np.float32)
    affine = np.eye(4)
    img = nib.Nifti1Image(data, affine)
    nib.save(img, TEST_FILE_PATH)
    print(f"Created {TEST_FILE_PATH}")

def login():
    """Login and get access token"""
    print("\nLogging in...")
    login_data = {
        "email": TEST_EMAIL,
        "password": TEST_PASSWORD
    }
    response = requests.post(f"{BASE_URL}/auth/login", json=login_data)
    if response.status_code == 200:
        token = response.json()["access_token"]
        print("✅ Login successful")
        return token
    else:
        print(f"❌ Login failed: {response.text}")
        return None

def upload_file(token):
    """Upload the dummy file"""
    print("\nUploading file...")
    headers = {"Authorization": f"Bearer {token}"}
    
    with open(TEST_FILE_PATH, "rb") as f:
        files = {"file": (TEST_FILE_PATH, f, "application/octet-stream")}
        data = {"patient_id": "PT-DEBUG-001"}
        response = requests.post(f"{BASE_URL}/upload", headers=headers, files=files, data=data)
    
    if response.status_code == 200:
        file_id = response.json()["file_id"]
        print(f"✅ Upload successful. File ID: {file_id}")
        return file_id
    else:
        print(f"❌ Upload failed: {response.text}")
        return None

def analyze_file(token, file_id):
    """Trigger analysis"""
    print(f"\nAnalyzing file {file_id}...")
    headers = {"Authorization": f"Bearer {token}"}
    
    start_time = time.time()
    response = requests.post(f"{BASE_URL}/analyze?file_id={file_id}", headers=headers)
    duration = time.time() - start_time
    
    if response.status_code == 200:
        result = response.json()
        print(f"✅ Analysis successful (took {duration:.2f}s)")
        return result
    else:
        print(f"❌ Analysis failed: {response.text}")
        return None

def check_results(result):
    """Check if results look real"""
    print("\nChecking results...")
    seg_data = result.get("segmentation", {})
    
    # Simulated: NCR volume = 3618.4
    ncr_vol = seg_data.get("regions", {}).get("NCR", {}).get("volume_mm3", 0)
    
    print(f"NCR Volume: {ncr_vol}")
    
    if ncr_vol == 3618.4:
        print("\n⚠️  REPRODUCED: Results match simulated data exactly.")
        print("The model inference failed for this file shape.")
    else:
        print("\n✅ Results look generated by the model!")

def main():
    try:
        create_dummy_2d_nifti()
        token = login()
        if not token: return
        
        file_id = upload_file(token)
        if not file_id: return
        
        result = analyze_file(token, file_id)
        if result:
            check_results(result)
            
    except Exception as e:
        print(f"\n❌ Error: {e}")
    finally:
        if os.path.exists(TEST_FILE_PATH):
            os.remove(TEST_FILE_PATH)
            print(f"\nCleaned up {TEST_FILE_PATH}")

if __name__ == "__main__":
    main()
